import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  gradient: { flex: 1 },
  container: { flex: 1, backgroundColor: 'transparent' },
  listGradient: { flex: 1 },
  time: { fontSize: 22, fontWeight: '600', marginTop: 20, marginLeft: 20 },
  dayBlock: { paddingVertical: 32, paddingHorizontal: 20, marginBottom: 0, borderRadius: 0 },
  dayHeader: { fontSize: 38, fontWeight: 'bold', marginBottom: 10 },
  taskRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#bbb',
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  taskTextWrap: { flex: 1 },
  taskText: { fontSize: 20 },
  completed: { textDecorationLine: 'line-through', color: '#888' },
  taskTime: { fontSize: 15, marginBottom: 2 },
  addTask: { fontSize: 18, marginTop: 10 },
  deleteBtn: { marginLeft: 10, padding: 4 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: 300,
    borderRadius: 16,
    padding: 24,
    alignItems: 'stretch',
    elevation: 5,
  },
  modalTitle: { fontSize: 24, fontWeight: 'bold', marginBottom: 16, textAlign: 'center' },
  input: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    fontSize: 18,
    marginBottom: 12,
  },
  modalBtns: { flexDirection: 'row', justifyContent: 'space-between' },
  modalBtn: { padding: 10 },
  themeToggleContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 18,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    pointerEvents: 'box-none',
  },
  themeToggleBtn: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 32,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles; 